/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginUserIdRouteImport } from './routes/login/$userId'
import { Route as AuthEventoRouteImport } from './routes/_auth.evento'
import { Route as AuthPresentesIndexRouteImport } from './routes/_auth.presentes/index'
import { Route as AuthParticipantesIndexRouteImport } from './routes/_auth.participantes/index'
import { Route as AuthPresentesNovoRouteImport } from './routes/_auth.presentes/novo'
import { Route as AuthParticipantesNovoRouteImport } from './routes/_auth.participantes/novo'
import { Route as AuthPresentesPresenteIdEditarRouteImport } from './routes/_auth.presentes/$presenteId/editar'
import { Route as AuthParticipantesUserIdEditarRouteImport } from './routes/_auth.participantes/$userId/editar'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUserIdRoute = LoginUserIdRouteImport.update({
  id: '/login/$userId',
  path: '/login/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEventoRoute = AuthEventoRouteImport.update({
  id: '/evento',
  path: '/evento',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPresentesIndexRoute = AuthPresentesIndexRouteImport.update({
  id: '/presentes/',
  path: '/presentes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParticipantesIndexRoute = AuthParticipantesIndexRouteImport.update({
  id: '/participantes/',
  path: '/participantes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPresentesNovoRoute = AuthPresentesNovoRouteImport.update({
  id: '/presentes/novo',
  path: '/presentes/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParticipantesNovoRoute = AuthParticipantesNovoRouteImport.update({
  id: '/participantes/novo',
  path: '/participantes/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPresentesPresenteIdEditarRoute =
  AuthPresentesPresenteIdEditarRouteImport.update({
    id: '/presentes/$presenteId/editar',
    path: '/presentes/$presenteId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthParticipantesUserIdEditarRoute =
  AuthParticipantesUserIdEditarRouteImport.update({
    id: '/participantes/$userId/editar',
    path: '/participantes/$userId/editar',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registrar': typeof RegistrarRoute
  '/terms': typeof TermsRoute
  '/evento': typeof AuthEventoRoute
  '/login/$userId': typeof LoginUserIdRoute
  '/login': typeof LoginIndexRoute
  '/participantes/novo': typeof AuthParticipantesNovoRoute
  '/presentes/novo': typeof AuthPresentesNovoRoute
  '/participantes': typeof AuthParticipantesIndexRoute
  '/presentes': typeof AuthPresentesIndexRoute
  '/participantes/$userId/editar': typeof AuthParticipantesUserIdEditarRoute
  '/presentes/$presenteId/editar': typeof AuthPresentesPresenteIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registrar': typeof RegistrarRoute
  '/terms': typeof TermsRoute
  '/evento': typeof AuthEventoRoute
  '/login/$userId': typeof LoginUserIdRoute
  '/login': typeof LoginIndexRoute
  '/participantes/novo': typeof AuthParticipantesNovoRoute
  '/presentes/novo': typeof AuthPresentesNovoRoute
  '/participantes': typeof AuthParticipantesIndexRoute
  '/presentes': typeof AuthPresentesIndexRoute
  '/participantes/$userId/editar': typeof AuthParticipantesUserIdEditarRoute
  '/presentes/$presenteId/editar': typeof AuthPresentesPresenteIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/registrar': typeof RegistrarRoute
  '/terms': typeof TermsRoute
  '/_auth/evento': typeof AuthEventoRoute
  '/login/$userId': typeof LoginUserIdRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/participantes/novo': typeof AuthParticipantesNovoRoute
  '/_auth/presentes/novo': typeof AuthPresentesNovoRoute
  '/_auth/participantes/': typeof AuthParticipantesIndexRoute
  '/_auth/presentes/': typeof AuthPresentesIndexRoute
  '/_auth/participantes/$userId/editar': typeof AuthParticipantesUserIdEditarRoute
  '/_auth/presentes/$presenteId/editar': typeof AuthPresentesPresenteIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registrar'
    | '/terms'
    | '/evento'
    | '/login/$userId'
    | '/login'
    | '/participantes/novo'
    | '/presentes/novo'
    | '/participantes'
    | '/presentes'
    | '/participantes/$userId/editar'
    | '/presentes/$presenteId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registrar'
    | '/terms'
    | '/evento'
    | '/login/$userId'
    | '/login'
    | '/participantes/novo'
    | '/presentes/novo'
    | '/participantes'
    | '/presentes'
    | '/participantes/$userId/editar'
    | '/presentes/$presenteId/editar'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/registrar'
    | '/terms'
    | '/_auth/evento'
    | '/login/$userId'
    | '/login/'
    | '/_auth/participantes/novo'
    | '/_auth/presentes/novo'
    | '/_auth/participantes/'
    | '/_auth/presentes/'
    | '/_auth/participantes/$userId/editar'
    | '/_auth/presentes/$presenteId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  RegistrarRoute: typeof RegistrarRoute
  TermsRoute: typeof TermsRoute
  LoginUserIdRoute: typeof LoginUserIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$userId': {
      id: '/login/$userId'
      path: '/login/$userId'
      fullPath: '/login/$userId'
      preLoaderRoute: typeof LoginUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/evento': {
      id: '/_auth/evento'
      path: '/evento'
      fullPath: '/evento'
      preLoaderRoute: typeof AuthEventoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/presentes/': {
      id: '/_auth/presentes/'
      path: '/presentes'
      fullPath: '/presentes'
      preLoaderRoute: typeof AuthPresentesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/participantes/': {
      id: '/_auth/participantes/'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof AuthParticipantesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/presentes/novo': {
      id: '/_auth/presentes/novo'
      path: '/presentes/novo'
      fullPath: '/presentes/novo'
      preLoaderRoute: typeof AuthPresentesNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/participantes/novo': {
      id: '/_auth/participantes/novo'
      path: '/participantes/novo'
      fullPath: '/participantes/novo'
      preLoaderRoute: typeof AuthParticipantesNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/presentes/$presenteId/editar': {
      id: '/_auth/presentes/$presenteId/editar'
      path: '/presentes/$presenteId/editar'
      fullPath: '/presentes/$presenteId/editar'
      preLoaderRoute: typeof AuthPresentesPresenteIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/participantes/$userId/editar': {
      id: '/_auth/participantes/$userId/editar'
      path: '/participantes/$userId/editar'
      fullPath: '/participantes/$userId/editar'
      preLoaderRoute: typeof AuthParticipantesUserIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthEventoRoute: typeof AuthEventoRoute
  AuthParticipantesNovoRoute: typeof AuthParticipantesNovoRoute
  AuthPresentesNovoRoute: typeof AuthPresentesNovoRoute
  AuthParticipantesIndexRoute: typeof AuthParticipantesIndexRoute
  AuthPresentesIndexRoute: typeof AuthPresentesIndexRoute
  AuthParticipantesUserIdEditarRoute: typeof AuthParticipantesUserIdEditarRoute
  AuthPresentesPresenteIdEditarRoute: typeof AuthPresentesPresenteIdEditarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEventoRoute: AuthEventoRoute,
  AuthParticipantesNovoRoute: AuthParticipantesNovoRoute,
  AuthPresentesNovoRoute: AuthPresentesNovoRoute,
  AuthParticipantesIndexRoute: AuthParticipantesIndexRoute,
  AuthPresentesIndexRoute: AuthPresentesIndexRoute,
  AuthParticipantesUserIdEditarRoute: AuthParticipantesUserIdEditarRoute,
  AuthPresentesPresenteIdEditarRoute: AuthPresentesPresenteIdEditarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  RegistrarRoute: RegistrarRoute,
  TermsRoute: TermsRoute,
  LoginUserIdRoute: LoginUserIdRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
