/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentesRouteImport } from './routes/presentes'
import { Route as ParticipantesRouteImport } from './routes/participantes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventoRouteImport } from './routes/evento'
import { Route as IndexRouteImport } from './routes/index'

const PresentesRoute = PresentesRouteImport.update({
  id: '/presentes',
  path: '/presentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantesRoute = ParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoRoute = EventoRouteImport.update({
  id: '/evento',
  path: '/evento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evento': typeof EventoRoute
  '/login': typeof LoginRoute
  '/participantes': typeof ParticipantesRoute
  '/presentes': typeof PresentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evento': typeof EventoRoute
  '/login': typeof LoginRoute
  '/participantes': typeof ParticipantesRoute
  '/presentes': typeof PresentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evento': typeof EventoRoute
  '/login': typeof LoginRoute
  '/participantes': typeof ParticipantesRoute
  '/presentes': typeof PresentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evento' | '/login' | '/participantes' | '/presentes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evento' | '/login' | '/participantes' | '/presentes'
  id: '__root__' | '/' | '/evento' | '/login' | '/participantes' | '/presentes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventoRoute: typeof EventoRoute
  LoginRoute: typeof LoginRoute
  ParticipantesRoute: typeof ParticipantesRoute
  PresentesRoute: typeof PresentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentes': {
      id: '/presentes'
      path: '/presentes'
      fullPath: '/presentes'
      preLoaderRoute: typeof PresentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participantes': {
      id: '/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof ParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento': {
      id: '/evento'
      path: '/evento'
      fullPath: '/evento'
      preLoaderRoute: typeof EventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventoRoute: EventoRoute,
  LoginRoute: LoginRoute,
  ParticipantesRoute: ParticipantesRoute,
  PresentesRoute: PresentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
